namespace: default
resources:
  - ../base
  - machine-deployment.yaml
patchesStrategicMerge:
  - patches/ipv6.yaml
  - patches/azure-cluster.yaml
  - patches/control-plane-adm-config.yaml
  - patches/control-plane-azure-template.yaml

