apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  kubeadmConfigSpec:
    preKubeadmCommands:
      # this is a workaround for the hairpin routing problem with internal load balancers
      # during kubeadm init where 10.128.0.100 is the internal LB IP.
      - if [ -f /tmp/kubeadm.yaml ]; then iptables -t nat -A OUTPUT -p all -d ${AZURE_INTERNAL_LB_IP} -j DNAT --to-destination 127.0.0.1; fi
