apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - https://docs.projectcalico.org/v3.20/manifests/calico-policy-only.yaml
patchesStrategicMerge:
    - patches/azure-mtu.yaml
patches:
- target: 
    group: apps
    version: v1
    kind: DaemonSet
    name: calico-node
    namespace: kube-system
  path: patches/calico-node.yaml
