apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - https://docs.projectcalico.org/v3.20/manifests/calico-vxlan.yaml
patchesStrategicMerge:
    - patches/azure-mtu.yaml
patches:
- path: patches/calico-node.yaml
  target:
    kind: DaemonSet
