on:
  push:
    branches:
    - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: "bash hack/install-go.sh"
    - run: "PATH=/usr/local/go/bin:$PATH make test-cover"
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
        fail_ci_if_error: true
